language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - valgrind

before_install:
  - cd Package

script:
  - |
    R CMD build .
    travis_wait 40 R CMD check --no-build-vignettes --no-manual --as-cran MSGARCH*tar.gz
  - R CMD install MSGARCH*tar.gz
  - cd tests
  - R -d valgrind "-f testthat.R --restore --save --no-readline --vanilla"
  
r:
  - devel
  - release
