language: r
sudo: required
cache: packages

r_packages:
  - devtools
  
os:
  - linux
  
addons:
  apt:
    packages:
      - valgrind

before_install:
  - cd Package

script:
  - |
    R CMD build .
    travis_wait 180 R CMD check --no-build-vignettes --no-manual --as-cran MSGARCH*tar.gz
  
r:
  - devel
  - release

after_success:
  - cat /home/travis/build/keblu/MSGARCH/Package/MSGARCH.Rcheck/tests/testthat.Rout
