language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - valgrind

before_install:
  - cd Package

script:
  - |
    R CMD build .
    travis_wait 40 R CMD check --no-build-vignettes --no-manual --use-valgrind -- as-cran MSGARCH*tar.gz
   
r:
  - devel
  - release
