language: r
sudo: false
cache: packages

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

addons:
  apt:
    packages:
      - valgrind

before_install:
  - cd Package

global:
   - _R_CRAN_CHECK_INCOMING_=true
   - _R_CHECK_CRAN_INCOMING_USE_ASPELL_=true
   - _R_CHECK_CRAN_INCOMING_USE_ASPELL_=true

r:
  - devel
  - release
