language: r
sudo: required
cache: packages

r_github_packages:
  - /keblu/MSGARCH/package
  
addons:
  apt:
    packages:
      - valgrind

before_install:
  - cd Package

script:
  - |
    R CMD build .
    travis_wait 40 R CMD check --no-build-vignettes --no-manual --as-cran MSGARCH*tar.gz
  
r:
  - devel
  - release

after_success:
  - Rscript -e 'library(MSGARCH); codecov()'
